---
sudo: false
language: ruby
cache: bundler
before_install: gem install bundler -v 1.17.3

rvm:
  - 2.4.5

services:
  - docker

before_install:
  - docker pull openvidu/openvidu-server-kms
  - docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms
